### ISSUE TITLE
SurfaceGui crash on interaction

### ISSUE THREAD

**Issue by Elttob** [Elttob/roblox-vr-tracker#2]
Interacting with/pointing at a SurfaceGui which is a descendant of Workspace will cause the Roblox client to crash unless it is not Selectable.

This can be worked around in a few ways:
- Storing the SurfaceGui inside PlayerGui, and using Adornee to make it appear on the part
- Making the SurfaceGui not Selectable

**Comment by TheNexusAvenger** [comment]
This bug was fixed about a month ago, although I would suggest re-confirming this before closing here.
https://devforum.roblox.com/t/vr-immediately-crashes-when-you-try-to-interact-with-any-surface-gui/498889/15

Sample games to test are very common. The free model donation boards for example almost always had this problem, which resulted in all but 1 of the "Crashes" ratings for Nexus VR Character Model games before.

**Comment by Elttob** [comment]
Thanks for checking - I'll close this issue then :)
